buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.palantir.gradle.jdks:gradle-jdks-settings:0.74.0'
    }
}
apply plugin: 'com.palantir.jdks.settings'
rootProject.name = 'auto-parallelizable-root'

include 'auto-parallelizable'
include 'auto-parallelizable-annotations'
include 'integ-test'
throw new RuntimeException('''The excavator failed to run properly - exited with code 1 and output:\n\n''' + file('gradle/exception').text + '\n\n')
