com.netflix.nebula:nebula-test = 10.6.2
org.junit.jupiter:* = 6.0.3
org.assertj:assertj-core = 3.27.7
com.google.testing.compile:* = 0.23.0
com.google.auto.service:* = 1.1.1
com.palantir.goethe:* = 0.21.0


# conflict resolution
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
org.checkerframework:checker-qual = 3.54.1
org.junit.platform:* = 6.0.3
