apply plugin: 'com.palantir.gradle-plugin-testing'
apply plugin: 'java-gradle-plugin'
apply plugin: 'groovy'

dependencies {
    annotationProcessor project(':auto-parallelizable')
    compileOnly project(':auto-parallelizable-annotations')

    // Dependency to enable injection into nebula-test
    testImplementation project(':auto-parallelizable')

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.netflix.nebula:nebula-test'
    testImplementation 'org.spockframework:spock-core'
    testCompileOnly 'junit:junit'
    testRuntimeOnly 'org.spockframework:spock-junit4'
}

gradleTestUtils {
    configurationCacheEnabled = true
}
